# Docker Compose file for KireMisu development environment

services:
  postgres:
    image: postgres:16-alpine
    container_name: kiremisu-postgres-dev
    environment:
      POSTGRES_DB: kiremisu
      POSTGRES_USER: kiremisu
      POSTGRES_PASSWORD: kiremisu
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kiremisu -d kiremisu"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - kiremisu-dev
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    container_name: kiremisu-backend-dev
    environment:
      - DATABASE_URL=postgresql+asyncpg://kiremisu:kiremisu@postgres:5432/kiremisu
      - SECRET_KEY=dev-secret-key-change-in-production
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
      - ALLOWED_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000"]
      - ENVIRONMENT=development
      # Default admin user configuration
      - DEFAULT_ADMIN_USERNAME=admin
      - DEFAULT_ADMIN_PASSWORD=KireMisu2025
      - DEFAULT_ADMIN_EMAIL=admin@kiremisu.local
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend:ro
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./manga-storage:/manga-storage:ro
    depends_on:
      postgres:
        condition: service_healthy
    command: ["uv", "run", "uvicorn", "kiremisu.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - kiremisu-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: kiremisu-frontend-dev
    environment:
      - BACKEND_URL=http://backend:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "dev"]
    networks:
      - kiremisu-dev
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local
  node_modules:
    driver: local

networks:
  kiremisu-dev:
    driver: bridge