version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://kiremisu:development@postgres:5432/kiremisu
      - SECRET_KEY=development-secret-key-change-in-production
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend:/app
      - manga-library:/manga
      - thumbnails:/thumbnails
      - processed-data:/processed
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: pnpm dev

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: kiremisu
      POSTGRES_USER: kiremisu
      POSTGRES_PASSWORD: development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kiremisu -d kiremisu"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  manga-library:
  thumbnails:
  processed-data: