"""Add compound indexes for job queue performance optimization

Revision ID: ad321789d335
Revises: cf4815a2275e
Create Date: 2025-08-04 18:58:29.402507

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad321789d335"
down_revision = "cf4815a2275e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_chapters_is_read"), "chapters", ["is_read"], unique=False)
    op.create_index("ix_chapters_read_at", "chapters", ["is_read", "read_at"], unique=False)
    op.create_index("ix_chapters_series_read", "chapters", ["series_id", "is_read"], unique=False)
    op.create_index("ix_job_queue_cleanup", "job_queue", ["status", "completed_at"], unique=False)
    op.create_index(
        "ix_job_queue_processing", "job_queue", ["status", "priority", "scheduled_at"], unique=False
    )
    op.create_index("ix_job_queue_retry", "job_queue", ["status", "retry_count"], unique=False)
    op.create_index("ix_job_queue_type_status", "job_queue", ["job_type", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_queue_type_status", table_name="job_queue")
    op.drop_index("ix_job_queue_retry", table_name="job_queue")
    op.drop_index("ix_job_queue_processing", table_name="job_queue")
    op.drop_index("ix_job_queue_cleanup", table_name="job_queue")
    op.drop_index("ix_chapters_series_read", table_name="chapters")
    op.drop_index("ix_chapters_read_at", table_name="chapters")
    op.drop_index(op.f("ix_chapters_is_read"), table_name="chapters")
    # ### end Alembic commands ###
