"""add color constraint to tags table

Revision ID: add_tag_color_constraint
Revises: dd79f52da30b
Create Date: 2025-08-05 02:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_tag_color_constraint'
down_revision: Union[str, None] = 'dd79f52da30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'ck_tag_color_format',
        'tags',
        "color IS NULL OR (color ~ '^#[0-9A-Fa-f]{6}$')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_tag_color_format', 'tags', type_='check')
    # ### end Alembic commands ###