"""add_tags_and_series_tags_tables

Revision ID: dd79f52da30b
Revises: 8b7fa7ea0263
Create Date: 2025-08-04 21:18:18.067800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd79f52da30b'
down_revision = '8b7fa7ea0263'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index('ix_tags_name_lower', 'tags', ['name'], unique=False, postgresql_ops={'name': 'varchar_ops'})
    op.create_index(op.f('ix_tags_usage_count'), 'tags', ['usage_count'], unique=False)
    op.create_index('ix_tags_usage_name', 'tags', ['usage_count', 'name'], unique=False)
    op.create_table('series_tags',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'tag_id')
    )
    op.create_index('ix_series_tags_series_id', 'series_tags', ['series_id'], unique=False)
    op.create_index('ix_series_tags_tag_id', 'series_tags', ['tag_id'], unique=False)
    op.drop_index(op.f('ix_chapters_read_at'), table_name='chapters')
    op.create_index(op.f('ix_chapters_read_at'), 'chapters', ['read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapters_read_at'), table_name='chapters')
    op.create_index(op.f('ix_chapters_read_at'), 'chapters', ['is_read', 'read_at'], unique=False)
    op.drop_index('ix_series_tags_tag_id', table_name='series_tags')
    op.drop_index('ix_series_tags_series_id', table_name='series_tags')
    op.drop_table('series_tags')
    op.drop_index('ix_tags_usage_name', table_name='tags')
    op.drop_index(op.f('ix_tags_usage_count'), table_name='tags')
    op.drop_index('ix_tags_name_lower', table_name='tags', postgresql_ops={'name': 'varchar_ops'})
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###