"""Add FileOperation model for safe file operations

Revision ID: dd79f52da30b
Revises: ad321789d335
Create Date: 2025-08-05 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ee80c53ea31c"
down_revision = "ad321789d335"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_operations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("operation_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("target_path", sa.Text(), nullable=True),
        sa.Column("backup_path", sa.Text(), nullable=True),
        sa.Column("affected_series_ids", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("affected_chapter_ids", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("operation_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validation_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rollback_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("validated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "operation_type IN ('rename', 'delete', 'move')", name="ck_file_operations_type"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'validated', 'in_progress', 'completed', 'failed', 'rolled_back')",
            name="ck_file_operations_status",
        ),
        sa.CheckConstraint("retry_count >= 0", name="ck_file_operations_retry_count"),
        sa.CheckConstraint("max_retries >= 0", name="ck_file_operations_max_retries"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_file_operations_status_created", "file_operations", ["status", "created_at"], unique=False
    )
    op.create_index(
        "ix_file_operations_type_status",
        "file_operations",
        ["operation_type", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_file_operations_operation_type"), "file_operations", ["operation_type"], unique=False)
    op.create_index(op.f("ix_file_operations_status"), "file_operations", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_operations_status"), table_name="file_operations")
    op.drop_index(op.f("ix_file_operations_operation_type"), table_name="file_operations")
    op.drop_index("ix_file_operations_type_status", table_name="file_operations")
    op.drop_index("ix_file_operations_status_created", table_name="file_operations")
    op.drop_table("file_operations")
    # ### end Alembic commands ###